version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - mysql
    networks:
      - test-network

  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/project
    networks:
      - test-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./docker/sql/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - mysqldata:/var/lib/mysql
    command:
      --default-authentication-plugin=mysql_native_password 
      --character-set-server=utf8mb4 
      --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: mvc.local
    networks:
      - test-network

networks:
  test-network:

volumes:
  mysqldata:
